version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - EMAIL_URL=smtp://mailhog:1025
    depends_on:
      - db
      - redis
      - mailhog
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: celery -A config worker -l info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - EMAIL_URL=smtp://mailhog:1025
    depends_on:
      - db
      - redis
      - mailhog

  beat:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: celery -A config beat -l info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - EMAIL_URL=smtp://mailhog:1025
    depends_on:
      - db
      - redis
      - mailhog

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  postgres_data:
